version: '3.3'

services:

  app:
    image: code4hr/okc-node
    build:
      context: .
      args:
        NODE_ENV: development
    # special startup script just for local development
    entrypoint: /usr/src/app/docker/docker-entrypoint-dev.sh 
    command: ../node_modules/.bin/nodemon server.js --inspect=0.0.0.0:9229
    environment:
      NODE_ENV: development
      OKC_DB_HOST: db
      OKC_DB_NAME: okcandidate_dev
      OKC_DB_USER: blaine
      OKC_DB_PASS: complicatedPassword
      OKC_SESSION_SECRET_KEY: someGobbledygookThatIsAtLeast32CharactersLong
      GOOGLE_API_KEY: google_api_key
    volumes:
      - .:/usr/src/app:delegated
        # for local dev only, we "hide" host-based node_modules so they don't conflict
      - notused:/usr/src/app/node_modules
    ports:
      - "80:3000"
      - "9229:9229"

  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: okcandidate_dev
      POSTGRES_USER: blaine
      POSTGRES_PASSWORD: complicatedPassword
    ports:
      - "5432:5432"

volumes:
  notused:
