version: '3.3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/okcandidate.crt:/etc/nginx/okcandidate.crt
      - ./docker/okcandidate.key:/etc/nginx/okcandidate.key
      - /data/nginx/cache
    ports:
      - "80:80"
      - "443:443"

  app:
    image: rydente/node:alpine-gyp
    env_file: .env
    command: "ash -c 'npm i && npm start'"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    env_file: .env
    image: postgres:alpine

