version: '3'
services:

  app:
    image: code4hr/okc-node
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"

  db:
    env_file: .env
    image: postgres:9.6.2-alpine

