version: '3.3'
services:

  api:
    build: ./backend/.
    environment:
      PORT: 8080
      NODE_ENV: development
      OKC_DB_HOST: db
      OKC_DB_NAME: okcandidate_dev
      OKC_DB_USER: blaine
      OKC_DB_PASS: complicatedPassword
      OKC_SESSION_SECRET_KEY: someGobbledygookThatIsAtLeast32CharactersLong
      GOOGLE_API_KEY: google_api_key
    volumes:
      - .:/usr/src/api
    ports:
      - "8080:8080"
      - "9229:9229"

  app:
    build: ./frontend/.
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"

  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: okcandidate_dev
      POSTGRES_USER: blaine
      POSTGRES_PASSWORD: complicatedPassword
    ports:
      - "5432:5432"


