version: '3.3'

services:

  app:
    image: code4hr/okc-node
    build:
      context: .
      args:
        NODE_ENV: development
    entrypoint: /usr/src/app/docker/docker-entrypoint.sh 
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229
    environment:
      NODE_ENV: development
      OKC_DB_HOST: db
      OKC_DB_NAME: okcandidate_platform_dev
      OKC_DB_USER: blaine
      OKC_DB_PASS: complicatedPassword
      OKC_SESSION_SECRET_KEY: someGobbledygookThatIsAtLeast32CharactersLong
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
      - "9229:9229"

  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB: okcandidate_platform_dev
      POSTGRES_USER: blaine
      POSTGRES_PASSWORD: complicatedPassword


