#!/usr/bin/env sh

# Copyright (c) 2016 code4hr <code4hr-team@codeforamerica.org> (http://code4hr.org/)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

openssl genrsa -out docker/root.key 2048
openssl req -x509 -new -nodes -key docker/root.key -sha256 -days 1024 -out docker/root.crt \
	-subj "/C=US/ST=Virginia/L=Norfolk/O=Code for Hampton Roads/OU=CWS/CN=Development Root CA"

openssl genrsa -out docker/okcandidate.key 2048
openssl req -new -key docker/okcandidate.key -out docker/okcandidate.csr \
        -subj "/C=US/ST=Virginia/L=Norfolk/O=Code for Hampton Roads/OU=CWS/CN=*.okcandidate.com"
openssl x509 -req -in docker/okcandidate.csr -CA docker/root.crt -CAkey docker/root.key \
        -CAcreateserial -out docker/okcandidate.original.crt -days 500 -sha256
cat docker/okcandidate.original.crt docker/root.crt > docker/okcandidate.crt

